name: "Build the nix development environment"
on:
  pull_request:
  push:
jobs:
  build_dev_env:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@6ed004b9ccb68dbc28e7c85bee15fa93dbd214ac  # v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix develop --impure